name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: main
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: main
      run: |
        pytest -q tests/

    - name: Build Docker image
      working-directory: main
      run: |
        docker build -t flask-lab-project:latest .

    # Optional: push to Docker Hub (requires secrets.DOCKERHUB_USERNAME and DOCKERHUB_TOKEN)
    - name: Log in to Docker Hub
      if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag & push image
      if: secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != ''
      run: |
        docker tag flask-lab-project:latest ${{ secrets.DOCKERHUB_USERNAME }}/flask-lab-project:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-lab-project:latest
